Update large_use_case
C2SM/c2sm.github.io pull request #230
Opened 2024-12-12 09:36 UTC by AnnikaLau

2024-12-13 10:14 UTC, mjaehn requested changes
Otherwise LGTM

2024-12-13 10:14 UTC, mjaehn commented on docs/models/icon/usage.md
> +### Sanits
```suggestion
### Santis
```

2024-12-13 12:44 UTC, AnnikaLau commented on docs/models/icon/usage.md
> +### Sanits
I don't see any difference?

2024-12-13 13:03 UTC, AnnikaLau commented
@mjaehn please approve!

2024-12-16 07:36 UTC, mjaehn approved these changes

2024-12-16 09:05 UTC, merged